// The Flow view: the real app's DOM (the mockup's app snapshot) filled with the shared tree. Read-only in T4b-1.
// Everything that came from the owner (names, notes) is written with textContent.
import {$, $$, el, iso} from "./dom.js";
import {applyDeclarations} from "./cssom.js";
import {wireDocs} from "./docs.js";

// Themes (ids, names and fonts are the mockup's, which are the app's: src/js/themeProfiles.js). The page wears the shared
// theme; the prototype takes its name from the server (precheck/flow read) if present, else FlowJoe's default.
export const THEMES = {
  "modern-ember": {name: "Modern Ember", font: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif'},
  "modern-paper": {name: "Modern Paper", font: 'Newsreader, "Source Serif 4", Georgia, "Times New Roman", serif'},
  "nord-1": {name: "Frost Ledger", font: '"IBM Plex Serif", "Source Serif 4", Georgia, "Times New Roman", serif'},
  "ghibli-1": {name: "Mist Canvas", font: 'Spectral, Lora, Georgia, "Times New Roman", serif'},
  "fern-1": {name: "Brass Fern", font: '"Playfair Display", "Source Serif 4", Georgia, "Times New Roman", serif'}
};
export const DEFAULT_THEME = "modern-ember";

export function applyTheme(id) {
  const themeId = Object.hasOwn(THEMES, id) ? id : DEFAULT_THEME;
  const root = document.documentElement;
  for (const t of Object.keys(THEMES)) root.classList.remove("theme-" + t);
  root.classList.add("theme-" + themeId);
  root.setAttribute("data-node-theme", themeId);
  root.style.setProperty("--app-font-family", THEMES[themeId].font);
  return themeId;
}

let SNAP = null;
let unitTemplate = null;

export async function loadSnapshot() {
  if (SNAP) return SNAP;
  const res = await fetch("/snapshot/snapshot.html", {cache: "no-store"}); // generated by build-snapshot.js: no style="" attributes, no <style> blocks
  if (!res.ok) throw new Error("snapshot");
  const doc = new DOMParser().parseFromString(await res.text(), "text/html");
  const tpl = (id) => doc.getElementById(id);
  const meta = tpl("snap-meta");
  SNAP = {
    htmlStyle: meta.dataset.htmlStyle,
    bodyClass: meta.dataset.bodyClass
      .split(/\s+/)
      .filter((c) => !["fj-bg-idle", "fj-ambient-freeze"].includes(c))
      .join(" "),
    html: ["snap-topbar", "snap-headerBg", "snap-container", "snap-footer"].map((id) => tpl(id).innerHTML).join("\n")
  };
  return SNAP;
}

// The app's root variables and body classes (radii, density, tokens). Needed by every screen, including the entry dialog.
export function prepareChrome() {
  applyDeclarations(document.documentElement, SNAP.htmlStyle); // CSSOM, not a style attribute (strict CSP)
  document.body.className = SNAP.bodyClass;
}

export function mountApp() {
  $("#snapRoot").innerHTML = SNAP.html; // a static, trusted file from this repo: no person's text is ever parsed as HTML
  const first = $(".enum-image-unit");
  unitTemplate = first ? first.cloneNode(true) : null;
  // The snapshot is a frozen demo Flow: wipe every piece of its demo content before anything is shown.
  $("#tree ul")?.replaceChildren();
  $(".image-gallery")
    ?.querySelectorAll(".enum-image-unit")
    .forEach((u) => u.remove());
  const tw = $("#tree-title");
  if (tw) {
    tw.value = "";
    tw.setAttribute("readonly", "");
  }
}

// ---- guest view: hide what a guest does not get; dim what a View guest cannot do -----------------------------------
const hideEl = (e) => {
  if (!e) return;
  e.hidden = true;
  e.style.setProperty("display", "none", "important");
};
function lock(e, tip) {
  if (!e) return;
  e.classList.add("cx-locked");
  e.setAttribute("aria-disabled", "true");
  e.setAttribute("data-cx-tooltip", tip);
}
function unlock(e) {
  if (!e) return;
  e.classList.remove("cx-locked");
  e.removeAttribute("aria-disabled");
  e.removeAttribute("data-cx-tooltip");
}

// Dims (View) or frees (Edit) the controls a View guest cannot use. Runs on EVERY render, so a role change in either direction
// (the owner downgrades or upgrades this guest) takes effect without a reload; the tip also follows the owner's name.
export function applyRoleLocks(S) {
  const viewTip = `You can view this Flow. Ask ${S.ownerName ? iso(S.ownerName) : "the owner"} for edit access`;
  const set = (e) => (S.role === "view" ? lock(e, viewTip) : unlock(e));
  for (const sel of ["#tree-add-node-btn", "#tree-add-image-btn", "#tree-delete-node-btn", "#delete-all-images", ".canvas-add-slot-btn"]) set($(sel));
  // A top-level node can only be added by the owner (the owner refuses it for every guest), so this stays dimmed for Edit guests too.
  lock($("#add-root"), S.role === "view" ? viewTip : "Only the owner can add a top-level node");
  for (const b of $$(".canvas-rail-add-btn, .canvas-rail-copy-btn, .canvas-rail-stack-btn, .canvas-rail-delete-btn, .gallery-tags-manager-btn")) set(b);
}

export function guestify(S) {
  S.presenceHost = $("#header-unsaved-indicator")?.parentElement || $(".topbar");
  for (const sel of ["#header-unsaved-indicator", "#file-menu-wrapper"]) hideEl($(sel));
  for (const sel of ["#cache-bust-btn", "#browser-btn", "#terminal-btn"]) {
    const b = $(sel);
    hideEl(b && (b.closest(".tooltip-wrapper") || b));
  }
  hideEl($(".topbar-settings-group"));
  for (const b of $$(".app-rail-item")) if (!["app-rail-flow-btn", "app-rail-joe-btn", "app-rail-docs-btn"].includes(b.id)) hideEl(b);
  wireDocs(); // G8
  for (const e of $$(".breadcrumb-storage-figure, .status-footer-scheduler")) hideEl(e);
  applyRoleLocks(S);
  // Add-a-slot (media) belongs to T4c; add/delete node are wired by edit.js for Edit guests.
  for (const sel of ["#tree-add-image-btn"]) $(sel)?.setAttribute("data-cx-slice", "t4c");
}

// The app renders tooltips through one body portal (.flowjoe-tooltip); a minimal stand-in for the locked controls.
export function wireTooltips() {
  const cxTip = el("div", {cls: "flowjoe-tooltip", attrs: {role: "tooltip"}});
  cxTip.appendChild(el("span", {cls: "cx-tip-text"}));
  document.body.appendChild(cxTip);
  const show = (target) => {
    cxTip.querySelector(".cx-tip-text").textContent = target.getAttribute("data-cx-tooltip");
    const r = target.getBoundingClientRect();
    cxTip.style.left = "0px";
    cxTip.style.top = "0px";
    cxTip.classList.add("is-visible");
    const w = cxTip.offsetWidth;
    cxTip.style.left = Math.max(8, Math.min(innerWidth - w - 8, r.left + r.width / 2 - w / 2)) + "px";
    cxTip.style.top = r.bottom + 8 + "px";
  };
  document.addEventListener("mouseover", (e) => {
    const t = e.target.closest("[data-cx-tooltip]");
    if (t) show(t);
    else cxTip.classList.remove("is-visible");
  });
  document.addEventListener("focusin", (e) => {
    const t = e.target.closest("[data-cx-tooltip]");
    if (t) show(t);
  });
  document.addEventListener("focusout", () => cxTip.classList.remove("is-visible"));
  document.addEventListener(
    "click",
    (e) => {
      if (e.target.closest(".cx-locked")) {
        e.preventDefault();
        e.stopPropagation();
      }
    },
    true
  );
}

// ---- data ------------------------------------------------------------------------------------------------------------
export function indexFlow(roots) {
  const byId = new Map();
  const parentOf = new Map();
  const walk = (list, parent) => {
    for (const n of list) {
      byId.set(n.id, n);
      parentOf.set(n.id, parent);
      walk(n.children || [], n.id);
    }
  };
  walk(roots, null);
  return {byId, parentOf};
}

function treeItem(node, selectedId, onSelect, nodeCount) {
  const li = el("li", {attrs: {draggable: "false", "data-node-id": node.id}});
  const row = el("div", {cls: "flex-container"});
  const text = el("span", {cls: "node-text", text: node.name, attrs: {dir: "auto"}});
  row.appendChild(text);
  const meta = el("span", {cls: "node-inline-meta"});
  if (node.locked) meta.appendChild(el("span", {cls: "image-count self-count", attrs: {title: "Locked by the owner"}, children: [el("i", {cls: "fa-solid fa-lock", attrs: {"aria-hidden": "true"}})]}));
  if ((node.children || []).length) meta.appendChild(el("span", {cls: "child-count expanded", text: `[${node.children.length}]`, attrs: {title: "Child nodes"}}));
  row.appendChild(meta);
  row.appendChild(el("div", {cls: "arrow-container"}));
  li.appendChild(row);
  if (node.id === selectedId) li.classList.add("selected");
  row.addEventListener("click", (e) => {
    e.stopPropagation();
    onSelect(node.id);
  });
  if ((node.children || []).length) {
    const ul = el("ul");
    for (const c of node.children) ul.appendChild(treeItem(c, selectedId, onSelect));
    li.appendChild(ul);
  }
  return li;
}

export function renderTree(S, onSelect) {
  const tree = $("#tree");
  let ul = $("ul", tree);
  if (!ul) {
    ul = el("ul");
    tree.appendChild(ul);
  }
  ul.replaceChildren();
  for (const r of S.roots) ul.appendChild(treeItem(r, S.selectedId, onSelect));
  const title = $("#tree-title");
  if (title) title.value = S.flowName || "Shared Flow";
}

function pathTo(S, id) {
  const chain = [];
  for (let n = id; n; n = S.parentOf.get(n)) chain.unshift(n);
  return chain;
}

export function renderBreadcrumb(S) {
  const text = $(".breadcrumbs-text");
  if (!text) return;
  for (const e of $$(".breadcrumb-flow, .breadcrumb-separator, .breadcrumb-link, .breadcrumb-current-node", text)) e.remove();
  const anchor = $("#gallery-summary-btn", text);
  const tail = $(".breadcrumb-storage-figure", text);
  const put = (node) => text.insertBefore(node, tail || null);
  const flow = el("span", {cls: "breadcrumb-flow", text: S.flowName || "Shared Flow", attrs: {title: S.flowName || "Shared Flow"}});
  applyDeclarations(flow, "color: var(--accent-color); font-weight: bold;");
  put(flow);
  const chain = S.selectedId ? pathTo(S, S.selectedId) : [];
  chain.forEach((id, i) => {
    put(el("span", {cls: "breadcrumb-separator", text: "›"}));
    const n = S.byId.get(id);
    if (i === chain.length - 1) {
      const cur = el("span", {cls: "breadcrumb-current-node", text: n.name, attrs: {title: n.name, dir: "auto"}});
      applyDeclarations(cur, "font-weight: normal !important;");
      put(cur);
    } else put(el("span", {cls: "breadcrumb-link breadcrumb-main", text: n.name, attrs: {title: n.name, dir: "auto"}}));
  });
  void anchor;
}

// The notes of the selected node, as one card in the real slot-card markup. (Slots/media are T4c: the guest read carries
// no media, so the card shows the node's own title and notes.)
export function renderCard(S) {
  const gallery = $(".image-gallery");
  if (!gallery) return;
  const draft = $("textarea.image-notes", gallery);
  const dirty = !!(draft && draft.dataset.dirty === "1");
  const keep = dirty && draft.dataset.nodeId === S.selectedId ? draft.value : null;
  gallery.querySelectorAll(".enum-image-unit:not(.gs-media-unit)").forEach((u) => u.remove()); // G3: media cards are kept (media.js reconciles them)
  gallery.style.transform = "none";
  const node = S.selectedId ? S.byId.get(S.selectedId) : null;
  hideEl($("#gallery-top-scrubber")); // the slot scrubber navigates media slots (T4c); the demo ticks must not show
  hideEl($("#gallery-top-scrubber-spacer"));
  if (!node || !unitTemplate) return;
  const canType = S.role === "edit" && !node.locked && !S.offline;
  const u = unitTemplate.cloneNode(true);
  for (const a of ["data-canvas-notes-sized-for-width", "data-canvas-slot-height", "data-canvas-slot-width", "data-canvas-rendered-height"]) u.removeAttribute(a);
  u.setAttribute("data-canvas-placed", "1"); // the app hides a canvas card until it is marked placed
  u.style.left = "32px";
  u.style.top = "196px";
  u.setAttribute("data-node-id", node.id);
  for (const sel of [".canvas-image-number", ".add-image-position", ".image-stack-container", ".gallery-tag-section", ".canvas-connect-handle", ".canvas-resize-handle", ".canvas-slot-title-drag-strip", ".canvas-slot-drag-grip", ".gallery-notes-hide-from-joe", ".gallery-notes-target-toggle", ".image-notes-content"]) u.querySelectorAll(sel).forEach((x) => x.remove());
  const title = $(".image-title", u);
  if (title) {
    for (const a of [...title.attributes]) if (a.name.startsWith("data-")) title.removeAttribute(a.name); // they carry the snapshot's demo title
    title.value = node.name;
    title.setAttribute("value", node.name);
    if (canType) title.removeAttribute("readonly");
    else title.setAttribute("readonly", "");
  }
  const label = $(".gallery-notes-titlebar-label", u);
  if (label) label.textContent = "Notes";
  const ta = $("textarea.image-notes", u);
  if (ta) {
    for (const a of [...ta.attributes]) if (a.name.startsWith("data-")) ta.removeAttribute(a.name); // demo notes live in data-notes-undo-prev-value
    ta.classList.remove("gallery-notes-tiptap-source-masked");
    ta.textContent = node.notes || ""; // the snapshot's demo notes are the textarea's child text; replace it
    ta.value = keep !== null ? keep : node.notes || "";
    ta.dataset.nodeId = node.id;
    ta.dataset.field = "notes";
    ta.rows = 6;
    ta.style.height = "auto";
    ta.style.minHeight = "9em";
    ta.style.textAlign = "start";
    if (keep !== null) ta.dataset.dirty = "1";
    if (!canType) ta.setAttribute("readonly", "");
    else ta.removeAttribute("readonly");
  }
  const col = $(".image-notes-column", u);
  if (col) col.classList.remove("gallery-notes-tiptap-host");
  if (node.locked && col) {
    const note = el("div", {cls: "cx-locked-note", attrs: {"data-locked-note": "1"}});
    note.appendChild(el("i", {cls: "fa-solid fa-lock", attrs: {"aria-hidden": "true"}}));
    note.appendChild(document.createTextNode(`Locked by ${S.ownerName ? iso(S.ownerName) : "the owner"}`));
    col.after(note);
  }
  gallery.appendChild(u);
}

function agoText(at) {
  const min = Math.floor((Date.now() - at) / 60000);
  return min < 1 ? "just now" : min < 60 ? `${min} min ago` : `${Math.floor(min / 60)} h ago`;
}

export function renderChrome(S) {
  const n = S.byId.size;
  const stats = $(".status-footer-stats .status-footer-text");
  if (stats) stats.textContent = `${n} shared node${n === 1 ? "" : "s"}`;
  const save = $(".status-footer-save .status-footer-text");
  if (save) save.textContent = S.offline ? `Offline \u00b7 last synced ${agoText(S.lastSynced)}` : `Synced to ${S.ownerName ? iso(S.ownerName) + "'s" : "the owner's"} FlowJoe`;
  const kbd = $(".status-footer-save .status-footer-kbd");
  if (kbd) kbd.style.display = "none";
  const dot = $(".status-footer-save .status-footer-dot");
  if (dot) dot.style.background = S.offline ? "var(--danger-color)" : "var(--success-color)";
  $(".status-footer-save")?.classList.remove("is-dirty");
  const th = $(".status-footer-theme .status-footer-text");
  if (th) th.textContent = THEMES[S.themeId].name + " · shared";
}

export function clearFlowView() {
  $("#snapRoot").replaceChildren();
  // the tooltip portal lives on <body>, outside #snapRoot, and may still hold "Ask <owner> for edit access"
  for (const t of $$(".flowjoe-tooltip")) {
    t.classList.remove("is-visible");
    for (const x of $$(".cx-tip-text", t)) x.textContent = "";
  }
}
