// Production build: owner addresses must be https, and the page does nothing when framed. (Generated by scripts/build-join-site.js.)
export const ownerBaseAllowed = (base) => typeof base === "string" && /^https:\/\/[a-z0-9.-]+$/.test(base);
export const refuseWhenFramed = true;
export const isFramed = (win) => {
  try {
    return win.top !== win.self;
  } catch (_) {
    return true;
  }
};
